server:
  port: 8668

spring:
  application:
    name: kob-server-processor
  datasource:
    username: root
    password: pwd
    url: jdbc:mysql://localhost:3306/kob?useUnicode=yes&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



debug: false

kob-schedule:
  zk-connect-string: localhost:2181
  zk-prefix: kob
  mysql-prefix: kob
  zk-auth-info:
  core:
    zk_servers: localhost:2181
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
  processor:
    task_push_threads: 36
    interval_min: 10
    waiting_task_scroll: 100