server:
  port: 8668

spring:
  application:
    name: kob-server-processor
  datasource:
    username: sa
    password: 1
    url: jdbc:sqlserver://localhost;DatabaseName=kob7
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false

kob-schedule:
  zk-connect-string: localhost:32770
  zk-prefix: kob
  mysql-prefix: kob
  zk-auth-info:
  core:
    zk_servers: localhost:32770
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
  processor:
    task_push_threads: 36
    interval_min: 10
    waiting_task_scroll: 100