server:
  port: 8668

spring:
  profiles:
    active: h2
  application:
    name: kob-server
  freemarker:
    template-loader-path: classpath:/templates/
    suffix:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



debug: false

kob-schedule:
  zk-connect-string: localhost:2181
  zk-prefix: kob
  mysql-prefix: kob
  zk-auth-info:
  core:
    zk_servers: localhost:2181
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
  processor:
    task_push_threads: 36
    interval_min: 10
    waiting_task_scroll: 100
