server:
  port: 8066

kob-schedule-client:
  project-code: kob_monitor
  zk-connect-string: localhost:32770
  zk-prefix: kob
  admin-url: http://localhost:8668/collect/system_collect.json
  log-warn-enable: true
  threads: 10
  zk-session-timeout: 4000
  zk-connection-timeout: 4000
#  zk-auth-info:
#    - scheme: 1
#      auth: 2

#kob.client:
#  env: official_develop
#  project_code: kob_monitor

#客户端快速实现配置的一种方式 详见：com.ke.kob.client.spring.env.OfficialDevelop
#或
#kob.client:
#  zp: incubator
#  project_code: kob_monitor
#  zk_servers: localhost_zk:2801
#  admin_url: http://localhost:8668
#  log_warn_enable: true